server:
  port: 8888

spring:
  application:
    name: config-service
  profiles:
    active: native
  cloud:
    config:
      server:
        native:
          search-locations: file://${user.home}///c:\Users\fhohf\native-file-repo
        git:
          uri: file:///C:\Users\fhohf\git-local-repo
